import type { Campaign } from "@/lib/types";
import { generateCampaign, type CampaignSeed } from "./_generator";

const seeds: CampaignSeed[] = [
  {
    id: "g-brand",
    name: "Brand — Značkové výrazy",
    platform: "google",
    type: "search",
    objective: "Konverzie / Tržby",
    status: "active",
    trend: "up",
    dailyBudget: 120,
    seed: 101,
    impressions: 3600,
    ctr: 11.5,
    cpc: 0.42,
    cvr: 9.2,
    aov: 72,
  },
  {
    id: "g-generic",
    name: "Search — Generické kľúčové slová",
    platform: "google",
    type: "search",
    objective: "Konverzie",
    status: "active",
    trend: "flat",
    dailyBudget: 240,
    seed: 202,
    impressions: 9800,
    ctr: 4.3,
    cpc: 0.71,
    cvr: 4.1,
    aov: 64,
  },
  {
    id: "g-competitor",
    name: "Search — Konkurenčné výrazy",
    platform: "google",
    type: "search",
    objective: "Konverzie",
    status: "limited",
    trend: "down",
    dailyBudget: 90,
    seed: 303,
    impressions: 5200,
    ctr: 3.1,
    cpc: 1.34,
    cvr: 2.4,
    aov: 58,
  },
  {
    id: "g-shopping-all",
    name: "Shopping — Celý katalóg",
    platform: "google",
    type: "shopping",
    objective: "Tržby",
    status: "active",
    trend: "up",
    dailyBudget: 300,
    seed: 404,
    impressions: 28000,
    ctr: 1.1,
    cpc: 0.38,
    cvr: 3.4,
    aov: 69,
  },
  {
    id: "g-shopping-best",
    name: "Shopping — Bestsellery",
    platform: "google",
    type: "shopping",
    objective: "Tržby",
    status: "active",
    trend: "flat",
    dailyBudget: 150,
    seed: 505,
    impressions: 12500,
    ctr: 1.4,
    cpc: 0.41,
    cvr: 4.6,
    aov: 81,
  },
  {
    id: "g-rmkt",
    name: "Display — Remarketing",
    platform: "google",
    type: "display",
    objective: "Konverzie",
    status: "active",
    trend: "up",
    dailyBudget: 70,
    seed: 606,
    impressions: 64000,
    ctr: 0.62,
    cpc: 0.17,
    cvr: 2.9,
    aov: 66,
  },
  {
    id: "g-prospecting",
    name: "Display — Prospecting nové publikum",
    platform: "google",
    type: "display",
    objective: "Povedomie / Návštevnosť",
    status: "paused",
    trend: "down",
    dailyBudget: 60,
    seed: 707,
    impressions: 88000,
    ctr: 0.41,
    cpc: 0.14,
    cvr: 0.7,
    aov: 52,
    pausedAfterDay: 76,
  },
  {
    id: "g-newcollection",
    name: "Search — Nová jarná kolekcia",
    platform: "google",
    type: "search",
    objective: "Konverzie",
    status: "learning",
    trend: "up",
    dailyBudget: 110,
    seed: 808,
    impressions: 7400,
    ctr: 3.8,
    cpc: 0.66,
    cvr: 3.0,
    aov: 61,
    activeFromDay: 72,
  },
];

export const googleCampaigns: Campaign[] = seeds.map(generateCampaign);
