import type { Campaign } from "@/lib/types";
import { generateCampaign, type CampaignSeed } from "./_generator";

const seeds: CampaignSeed[] = [
  {
    id: "m-awareness",
    name: "Awareness — Povedomie o značke",
    platform: "meta",
    type: "awareness",
    objective: "Dosah / Povedomie",
    status: "active",
    trend: "flat",
    dailyBudget: 80,
    seed: 111,
    impressions: 142000,
    ctr: 0.58,
    cpc: 0.13,
    cvr: 0.5,
    aov: 54,
    hasReach: true,
    frequency: 2.4,
  },
  {
    id: "m-launch",
    name: "Awareness — Launch novej kolekcie",
    platform: "meta",
    type: "awareness",
    objective: "Dosah / Povedomie",
    status: "learning",
    trend: "up",
    dailyBudget: 130,
    seed: 222,
    impressions: 96000,
    ctr: 0.74,
    cpc: 0.16,
    cvr: 0.9,
    aov: 63,
    hasReach: true,
    frequency: 1.9,
    activeFromDay: 74,
  },
  {
    id: "m-traffic",
    name: "Traffic — Návštevnosť e-shopu",
    platform: "meta",
    type: "traffic",
    objective: "Návštevnosť",
    status: "active",
    trend: "up",
    dailyBudget: 95,
    seed: 333,
    impressions: 58000,
    ctr: 1.28,
    cpc: 0.27,
    cvr: 1.8,
    aov: 59,
    hasReach: true,
    frequency: 2.1,
  },
  {
    id: "m-traffic-blog",
    name: "Traffic — Blog a obsahový marketing",
    platform: "meta",
    type: "traffic",
    objective: "Návštevnosť",
    status: "active",
    trend: "down",
    dailyBudget: 45,
    seed: 444,
    impressions: 41000,
    ctr: 1.05,
    cpc: 0.23,
    cvr: 0.9,
    aov: 48,
    hasReach: true,
    frequency: 2.8,
  },
  {
    id: "m-retarget",
    name: "Conversion — Retargeting košík",
    platform: "meta",
    type: "conversion",
    objective: "Konverzie / Tržby",
    status: "active",
    trend: "up",
    dailyBudget: 110,
    seed: 555,
    impressions: 34000,
    ctr: 1.72,
    cpc: 0.31,
    cvr: 6.2,
    aov: 74,
    hasReach: true,
    frequency: 3.2,
  },
  {
    id: "m-prospect",
    name: "Conversion — Prospecting nákupy",
    platform: "meta",
    type: "conversion",
    objective: "Konverzie / Tržby",
    status: "limited",
    trend: "flat",
    dailyBudget: 100,
    seed: 666,
    impressions: 72000,
    ctr: 1.14,
    cpc: 0.34,
    cvr: 2.1,
    aov: 67,
    hasReach: true,
    frequency: 1.7,
  },
];

export const metaCampaigns: Campaign[] = seeds.map(generateCampaign);
